spring:
  application:
    name: FeedbackService
  config:
    import: configserver:https://ra-cs-prod.up.railway.app/
  profiles:
    active: default     
 
management:
  security:
    enabled: false